# I will examine the efficacy of a logistic regressor on the engineered dataset to predict team1 win or lose

In [1]:
import pandas as pd
df = pd.read_csv("../../data/rolling_feature_engineered_tier_1_games.csv")
df

,previous_10_game_team1_player1_average_kills,previous_10_game_team1_player1_average_deaths,previous_10_game_team1_player1_average_assists,previous_10_game_team1_player1_average_adr,previous_10_game_team1_player1_average_kast,previous_10_game_team1_player1_average_kddiff,previous_10_game_team1_player2_average_kills,previous_10_game_team1_player2_average_deaths,previous_10_game_team1_player2_average_assists,previous_10_game_team1_player2_average_adr,...,team1_player1_id,team1_player2_id,team1_player3_id,team1_player4_id,team1_player5_id,team2_player1_id,team2_player2_id,team2_player3_id,team2_player4_id,team2_player5_id
0,16.000000,15.000000,4.000000,75.000000,70.000000,1.000000,16.000000,15.000000,4.000000,75.000000,...,553.0,39.0,612.0,163.0,457.0,739.0,1443.0,65.0,2049.0,209.0
1,12.000000,17.000000,4.000000,59.100000,62.500000,-5.000000,13.000000,11.000000,2.000000,52.600000,...,553.0,39.0,612.0,163.0,457.0,739.0,1443.0,65.0,2049.0,209.0
2,13.500000,16.500000,4.500000,66.250000,71.750000,-3.000000,18.500000,11.000000,4.000000,82.550000,...,553.0,39.0,612.0,163.0,457.0,739.0,1443.0,65.0,2049.0,209.0
3,14.612903,14.645161,4.258065,69.832258,71.535484,-0.032258,14.612903,14.645161,4.258065,69.832258,...,3202.0,1420.0,3168.0,607.0,3032.0,3836.0,1886.0,2588.0,1778.0,4567.0
4,13.000000,5.000000,1.000000,81.300000,86.700000,8.000000,11.000000,6.000000,4.000000,72.100000,...,3202.0,1420.0,3168.0,607.0,3032.0,3836.0,1886.0,2588.0,1778.0,4567.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5534,15.400000,14.800000,4.900000,73.770000,77.820000,0.600000,14.200000,12.900000,3.900000,66.030000,...,2988.0,266.0,7528.0,6900.0,16113.0,1401.0,169.0,1834.0,2934.0,7201.0
5535,16.600000,15.500000,5.000000,76.570000,76.160000,1.100000,14.900000,13.400000,3.900000,66.480000,...,2988.0,266.0,7528.0,6900.0,16113.0,1401.0,169.0,1834.0,2934.0,7201.0
5536,15.400000,15.900000,4.600000,73.230000,73.160000,-0.500000,14.800000,13.600000,3.700000,66.540000,...,2988.0,266.0,7528.0,6900.0,16113.0,1401.0,169.0,1834.0,2934.0,7201.0
5537,13.300000,13.400000,4.500000,67.660000,73.790000,-0.100000,10.700000,13.700000,5.800000,57.120000,...,1401.0,169.0,1834.0,2934.0,7201.0,19.0,550.0,1549.0,1443.0,146.0
5538,12.700000,14.000000,4.100000,65.910000,71.220000,-1.300000,11.100000,13.600000,5.900000,59.090000,...,1401.0,169.0,1834.0,2934.0,7201.0,19.0,550.0,1549.0,1443.0,146.0

In [2]:
df.columns

Index(['previous_10_game_team1_player1_average_kills',
       'previous_10_game_team1_player1_average_deaths',
       'previous_10_game_team1_player1_average_assists',
       'previous_10_game_team1_player1_average_adr',
       'previous_10_game_team1_player1_average_kast',
       'previous_10_game_team1_player1_average_kddiff',
       'previous_10_game_team1_player2_average_kills',
       'previous_10_game_team1_player2_average_deaths',
       'previous_10_game_team1_player2_average_assists',
       'previous_10_game_team1_player2_average_adr',
       'previous_10_game_team1_player2_average_kast',
       'previous_10_game_team1_player2_average_kddiff',
       'previous_10_game_team1_player3_average_kills',
       'previous_10_game_team1_player3_average_deaths',
       'previous_10_game_team1_player3_average_assists',
       'previous_10_game_team1_player3_average_adr',
       'previous_10_game_team1_player3_average_kast',
       'previous_10_game_team1_player3_average_kddiff',
       'previous_10_game_team1_player4_average_kills',
       'previous_10_game_team1_player4_average_deaths',
       'previous_10_game_team1_player4_average_assists',
       'previous_10_game_team1_player4_average_adr',
       'previous_10_game_team1_player4_average_kast',
       'previous_10_game_team1_player4_average_kddiff',
       'previous_10_game_team1_player5_average_kills',
       'previous_10_game_team1_player5_average_deaths',
       'previous_10_game_team1_player5_average_assists',
       'previous_10_game_team1_player5_average_adr',
       'previous_10_game_team1_player5_average_kast',
       'previous_10_game_team1_player5_average_kddiff',
       'previous_10_game_team2_player1_average_kills',
       'previous_10_game_team2_player1_average_deaths',
       'previous_10_game_team2_player1_average_assists',
       'previous_10_game_team2_player1_average_adr',
       'previous_10_game_team2_player1_average_kast',
       'previous_10_game_team2_player1_average_kddiff',
       'previous_10_game_team2_player2_average_kills',
       'previous_10_game_team2_player2_average_deaths',
       'previous_10_game_team2_player2_average_assists',
       'previous_10_game_team2_player2_average_adr',
       'previous_10_game_team2_player2_average_kast',
       'previous_10_game_team2_player2_average_kddiff',
       'previous_10_game_team2_player3_average_kills',
       'previous_10_game_team2_player3_average_deaths',
       'previous_10_game_team2_player3_average_assists',
       'previous_10_game_team2_player3_average_adr',
       'previous_10_game_team2_player3_average_kast',
       'previous_10_game_team2_player3_average_kddiff',
       'previous_10_game_team2_player4_average_kills',
       'previous_10_game_team2_player4_average_deaths',
       'previous_10_game_team2_player4_average_assists',
       'previous_10_game_team2_player4_average_adr',
       'previous_10_game_team2_player4_average_kast',
       'previous_10_game_team2_player4_average_kddiff',
       'previous_10_game_team2_player5_average_kills',
       'previous_10_game_team2_player5_average_deaths',
       'previous_10_game_team2_player5_average_assists',
       'previous_10_game_team2_player5_average_adr',
       'previous_10_game_team2_player5_average_kast',
       'previous_10_game_team2_player5_average_kddiff', 'team1_win', 'team1',
       'team2', 'team1_id', 'team2_id', 'game_id', 'match_id', 'tournament',
       'bestOf', 'map_id', 'map_name', 'datetime',
       'team1_previous_10_average_map_score',
       'team2_previous_10_average_map_score', 'team1_player1_id',
       'team1_player2_id', 'team1_player3_id', 'team1_player4_id',
       'team1_player5_id', 'team2_player1_id', 'team2_player2_id',
       'team2_player3_id', 'team2_player4_id', 'team2_player5_id'],
      dtype='object')

I'm going to drop arbitrary data like ids and names

In [3]:
to_drop = []
to_drop.extend([f"team{i}_player{k}_id" for i in range(1,3) for k in range(1,6)])
to_drop.extend([f"team{i}_id" for i in range(1,3)])
to_drop.extend([f"team{i}" for i in range(1,3)])
to_drop.extend(["tournament", "match_id", "game_id", "map_id", "map_name", "datetime"])
df = df.drop(to_drop, axis=1)
df

,previous_10_game_team1_player1_average_kills,previous_10_game_team1_player1_average_deaths,previous_10_game_team1_player1_average_assists,previous_10_game_team1_player1_average_adr,previous_10_game_team1_player1_average_kast,previous_10_game_team1_player1_average_kddiff,previous_10_game_team1_player2_average_kills,previous_10_game_team1_player2_average_deaths,previous_10_game_team1_player2_average_assists,previous_10_game_team1_player2_average_adr,...,previous_10_game_team2_player5_average_kills,previous_10_game_team2_player5_average_deaths,previous_10_game_team2_player5_average_assists,previous_10_game_team2_player5_average_adr,previous_10_game_team2_player5_average_kast,previous_10_game_team2_player5_average_kddiff,team1_win,bestOf,team1_previous_10_average_map_score,team2_previous_10_average_map_score
0,16.000000,15.000000,4.000000,75.000000,70.000000,1.000000,16.000000,15.000000,4.000000,75.000000,...,16.000000,15.000000,4.000000,75.000000,70.000000,1.000000,0,3.0,13.000000,13.000000
1,12.000000,17.000000,4.000000,59.100000,62.500000,-5.000000,13.000000,11.000000,2.000000,52.600000,...,13.000000,16.000000,4.000000,49.000000,58.300000,-3.000000,1,3.0,12.333333,12.333333
2,13.500000,16.500000,4.500000,66.250000,71.750000,-3.000000,18.500000,11.000000,4.000000,82.550000,...,11.000000,16.500000,5.000000,61.500000,60.100000,-5.500000,1,3.0,11.600000,11.600000
3,14.612903,14.645161,4.258065,69.832258,71.535484,-0.032258,14.612903,14.645161,4.258065,69.832258,...,14.612903,14.645161,4.258065,69.832258,71.535484,-0.032258,1,3.0,11.571429,11.571429
4,13.000000,5.000000,1.000000,81.300000,86.700000,8.000000,11.000000,6.000000,4.000000,72.100000,...,2.000000,14.000000,0.000000,23.500000,26.700000,-12.000000,1,3.0,10.666667,10.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5534,15.400000,14.800000,4.900000,73.770000,77.820000,0.600000,14.200000,12.900000,3.900000,66.030000,...,18.600000,15.800000,7.600000,93.320000,77.400000,2.800000,0,3.0,13.400000,9.500000
5535,16.600000,15.500000,5.000000,76.570000,76.160000,1.100000,14.900000,13.400000,3.900000,66.480000,...,19.100000,15.900000,6.800000,90.800000,76.820000,3.200000,0,3.0,9.700000,11.100000
5536,15.400000,15.900000,4.600000,73.230000,73.160000,-0.500000,14.800000,13.600000,3.700000,66.540000,...,19.900000,16.000000,6.700000,90.800000,75.820000,3.900000,1,3.0,11.000000,10.700000
5537,13.300000,13.400000,4.500000,67.660000,73.790000,-0.100000,10.700000,13.700000,5.800000,57.120000,...,16.600000,11.400000,4.500000,82.410000,82.000000,5.200000,0,5.0,11.400000,12.700000
5538,12.700000,14.000000,4.100000,65.910000,71.220000,-1.300000,11.100000,13.600000,5.900000,59.090000,...,16.700000,11.100000,4.000000,81.540000,82.430000,5.600000,0,5.0,10.700000,13.300000

In [4]:
df.columns

Index(['previous_10_game_team1_player1_average_kills',
       'previous_10_game_team1_player1_average_deaths',
       'previous_10_game_team1_player1_average_assists',
       'previous_10_game_team1_player1_average_adr',
       'previous_10_game_team1_player1_average_kast',
       'previous_10_game_team1_player1_average_kddiff',
       'previous_10_game_team1_player2_average_kills',
       'previous_10_game_team1_player2_average_deaths',
       'previous_10_game_team1_player2_average_assists',
       'previous_10_game_team1_player2_average_adr',
       'previous_10_game_team1_player2_average_kast',
       'previous_10_game_team1_player2_average_kddiff',
       'previous_10_game_team1_player3_average_kills',
       'previous_10_game_team1_player3_average_deaths',
       'previous_10_game_team1_player3_average_assists',
       'previous_10_game_team1_player3_average_adr',
       'previous_10_game_team1_player3_average_kast',
       'previous_10_game_team1_player3_average_kddiff',
       'previous_10_game_team1_player4_average_kills',
       'previous_10_game_team1_player4_average_deaths',
       'previous_10_game_team1_player4_average_assists',
       'previous_10_game_team1_player4_average_adr',
       'previous_10_game_team1_player4_average_kast',
       'previous_10_game_team1_player4_average_kddiff',
       'previous_10_game_team1_player5_average_kills',
       'previous_10_game_team1_player5_average_deaths',
       'previous_10_game_team1_player5_average_assists',
       'previous_10_game_team1_player5_average_adr',
       'previous_10_game_team1_player5_average_kast',
       'previous_10_game_team1_player5_average_kddiff',
       'previous_10_game_team2_player1_average_kills',
       'previous_10_game_team2_player1_average_deaths',
       'previous_10_game_team2_player1_average_assists',
       'previous_10_game_team2_player1_average_adr',
       'previous_10_game_team2_player1_average_kast',
       'previous_10_game_team2_player1_average_kddiff',
       'previous_10_game_team2_player2_average_kills',
       'previous_10_game_team2_player2_average_deaths',
       'previous_10_game_team2_player2_average_assists',
       'previous_10_game_team2_player2_average_adr',
       'previous_10_game_team2_player2_average_kast',
       'previous_10_game_team2_player2_average_kddiff',
       'previous_10_game_team2_player3_average_kills',
       'previous_10_game_team2_player3_average_deaths',
       'previous_10_game_team2_player3_average_assists',
       'previous_10_game_team2_player3_average_adr',
       'previous_10_game_team2_player3_average_kast',
       'previous_10_game_team2_player3_average_kddiff',
       'previous_10_game_team2_player4_average_kills',
       'previous_10_game_team2_player4_average_deaths',
       'previous_10_game_team2_player4_average_assists',
       'previous_10_game_team2_player4_average_adr',
       'previous_10_game_team2_player4_average_kast',
       'previous_10_game_team2_player4_average_kddiff',
       'previous_10_game_team2_player5_average_kills',
       'previous_10_game_team2_player5_average_deaths',
       'previous_10_game_team2_player5_average_assists',
       'previous_10_game_team2_player5_average_adr',
       'previous_10_game_team2_player5_average_kast',
       'previous_10_game_team2_player5_average_kddiff', 'team1_win', 'bestOf',
       'team1_previous_10_average_map_score',
       'team2_previous_10_average_map_score'],
      dtype='object')

Note that even after dropping that data, we still have a lot of dimensions to this data (63 features)

Let's now one-hot encode bestOf (I suspect this has little influence on the result whatsoever, but we will see)

In [5]:
bestOf_cats = pd.get_dummies(df.bestOf, drop_first=True, prefix="bestOf", dtype=int)
df = df.drop("bestOf", axis=1)

In [6]:
df.head(5)

,previous_10_game_team1_player1_average_kills,previous_10_game_team1_player1_average_deaths,previous_10_game_team1_player1_average_assists,previous_10_game_team1_player1_average_adr,previous_10_game_team1_player1_average_kast,previous_10_game_team1_player1_average_kddiff,previous_10_game_team1_player2_average_kills,previous_10_game_team1_player2_average_deaths,previous_10_game_team1_player2_average_assists,previous_10_game_team1_player2_average_adr,...,previous_10_game_team2_player4_average_kddiff,previous_10_game_team2_player5_average_kills,previous_10_game_team2_player5_average_deaths,previous_10_game_team2_player5_average_assists,previous_10_game_team2_player5_average_adr,previous_10_game_team2_player5_average_kast,previous_10_game_team2_player5_average_kddiff,team1_win,team1_previous_10_average_map_score,team2_previous_10_average_map_score
0,16.000000,15.000000,4.000000,75.000000,70.000000,1.000000,16.000000,15.000000,4.000000,75.000000,...,1.000000,16.000000,15.000000,4.000000,75.000000,70.000000,1.000000,0,13.000000,13.000000
1,12.000000,17.000000,4.000000,59.100000,62.500000,-5.000000,13.000000,11.000000,2.000000,52.600000,...,1.000000,13.000000,16.000000,4.000000,49.000000,58.300000,-3.000000,1,12.333333,12.333333
2,13.500000,16.500000,4.500000,66.250000,71.750000,-3.000000,18.500000,11.000000,4.000000,82.550000,...,-1.500000,11.000000,16.500000,5.000000,61.500000,60.100000,-5.500000,1,11.600000,11.600000
3,14.612903,14.645161,4.258065,69.832258,71.535484,-0.032258,14.612903,14.645161,4.258065,69.832258,...,-0.032258,14.612903,14.645161,4.258065,69.832258,71.535484,-0.032258,1,11.571429,11.571429
4,13.000000,5.000000,1.000000,81.300000,86.700000,8.000000,11.000000,6.000000,4.000000,72.100000,...,-11.000000,2.000000,14.000000,0.000000,23.500000,26.700000,-12.000000,1,10.666667,10.666667

Now, let's do our train/test split and do feature standardization

In [7]:
import math
from sklearn.preprocessing import StandardScaler
split_point = math.ceil(len(df) * 0.8)
# SPLIT MUST BE TEMPORAL TO AVOID TEST LEAKAGE INTO TRAIN SINCE
# FEATURES ARE CUMULATIVE
train = df.iloc[:split_point] # 0 to split_point - 1
test = df.iloc[split_point:] # split_point to len(df)
X_train = train.drop("team1_win", axis=1)
y_train = train.team1_win
X_test = test.drop("team1_win", axis=1)
y_test = test.team1_win
stnd = StandardScaler().set_output(transform="pandas")
X_train = stnd.fit_transform(X_train)
X_test = stnd.transform(X_test)

Now add back the categorical features

In [8]:
train_cat = bestOf_cats.iloc[:split_point]
test_cat = bestOf_cats.iloc[split_point:]
X_train = pd.concat([X_train, train_cat], axis=1)
X_test = pd.concat([X_test, test_cat], axis=1)
display(X_train.head())
display(X_test.head())

,previous_10_game_team1_player1_average_kills,previous_10_game_team1_player1_average_deaths,previous_10_game_team1_player1_average_assists,previous_10_game_team1_player1_average_adr,previous_10_game_team1_player1_average_kast,previous_10_game_team1_player1_average_kddiff,previous_10_game_team1_player2_average_kills,previous_10_game_team1_player2_average_deaths,previous_10_game_team1_player2_average_assists,previous_10_game_team1_player2_average_adr,...,previous_10_game_team2_player5_average_kills,previous_10_game_team2_player5_average_deaths,previous_10_game_team2_player5_average_assists,previous_10_game_team2_player5_average_adr,previous_10_game_team2_player5_average_kast,previous_10_game_team2_player5_average_kddiff,team1_previous_10_average_map_score,team2_previous_10_average_map_score,bestOf_3.0,bestOf_5.0
0,0.783380,0.414983,-1.043853,0.214328,-0.403623,0.389473,0.598443,0.365273,-0.961984,0.116140,...,0.711126,0.344597,-0.734972,0.336253,-0.283432,0.398672,1.067406,1.103525,1,0
1,-1.024439,1.577825,-1.043853,-1.714085,-1.986267,-1.902497,-0.642823,-2.095518,-2.772332,-2.293183,...,-0.520292,0.907973,-0.734972,-2.578797,-2.585610,-1.024151,0.694554,0.753637,1,0
2,-0.346507,1.287115,-0.639153,-0.846905,-0.034339,-1.138507,1.632831,-2.095518,-0.961984,0.928211,...,-1.341238,1.189661,0.173416,-1.177331,-2.231429,-1.913416,0.284417,0.368761,1,0
3,0.156475,0.208672,-0.834975,-0.412435,-0.079606,-0.004844,0.024524,0.146977,-0.728391,-0.439698,...,0.141761,0.144690,-0.500549,-0.243141,0.018701,0.031492,0.268438,0.353766,1,0
4,-0.572484,-5.399230,-3.472052,0.978417,3.120397,3.063438,-1.470334,-5.171508,-0.961984,-0.195781,...,-5.035494,-0.218779,-4.368525,-5.437788,-8.803459,-4.225505,-0.237576,-0.121081,1,0

,previous_10_game_team1_player1_average_kills,previous_10_game_team1_player1_average_deaths,previous_10_game_team1_player1_average_assists,previous_10_game_team1_player1_average_adr,previous_10_game_team1_player1_average_kast,previous_10_game_team1_player1_average_kddiff,previous_10_game_team1_player2_average_kills,previous_10_game_team1_player2_average_deaths,previous_10_game_team1_player2_average_assists,previous_10_game_team1_player2_average_adr,...,previous_10_game_team2_player5_average_kills,previous_10_game_team2_player5_average_deaths,previous_10_game_team2_player5_average_assists,previous_10_game_team2_player5_average_adr,previous_10_game_team2_player5_average_kast,previous_10_game_team2_player5_average_kddiff,team1_previous_10_average_map_score,team2_previous_10_average_map_score,bestOf_3.0,bestOf_5.0
4432,1.144944,-0.399007,-0.153513,1.131234,0.047958,1.229862,-1.387583,-0.311444,2.025089,-1.602654,...,-0.397151,-0.613142,0.082577,0.116503,-0.930796,0.042966,0.578038,-0.018424,1,0
4433,-0.934048,-1.678134,-1.286673,-0.762006,0.632481,0.313074,0.681194,-1.849439,-0.418880,1.606908,...,-0.109819,0.119247,0.627610,0.128836,0.285226,-0.170457,0.060706,0.158829,1,0
4434,-1.069635,-1.968844,-1.853252,-1.043385,0.923688,0.389473,0.432941,-1.972479,-0.147328,1.652083,...,-0.438198,-0.106104,0.536771,-0.046067,0.243905,-0.312740,0.396273,-0.785868,1,0
4435,-0.662875,-1.968844,-1.934192,-0.674682,0.826619,0.733269,0.267439,-1.972479,-0.328363,1.618740,...,-0.438198,-0.331454,0.809288,-0.006826,0.153392,-0.170457,-0.330789,0.368761,1,0
4436,-0.843657,0.414983,0.170247,-0.999723,-1.055672,-0.985709,-0.270444,0.795912,-1.324054,-0.250637,...,0.382748,-0.444129,0.082577,0.200591,0.180939,0.612096,0.508128,-0.995800,1,0

Now we can train our logistic regressor

In [9]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()

In [10]:
lr.score(X_train, y_train)

0.592057761732852

In [11]:
((y_train == y_train.mode()[0]).sum()) / len(y_train)

np.float64(0.5464801444043321)

It is 59% accurate, so it only performs ~5% better than the baseline.

In [12]:
lr.score(X_test, y_test)

0.5546522131887985

In [13]:
((y_test == y_train.mode()[0]).sum()) / len(y_test)

np.float64(0.5582655826558266)

The logistic regressor performs ~0.4% worse on the test set compared to the baseline.

I'm curious which features it deems most important

In [14]:
display(X_train.columns)
display(lr.coef_)

Index(['previous_10_game_team1_player1_average_kills',
       'previous_10_game_team1_player1_average_deaths',
       'previous_10_game_team1_player1_average_assists',
       'previous_10_game_team1_player1_average_adr',
       'previous_10_game_team1_player1_average_kast',
       'previous_10_game_team1_player1_average_kddiff',
       'previous_10_game_team1_player2_average_kills',
       'previous_10_game_team1_player2_average_deaths',
       'previous_10_game_team1_player2_average_assists',
       'previous_10_game_team1_player2_average_adr',
       'previous_10_game_team1_player2_average_kast',
       'previous_10_game_team1_player2_average_kddiff',
       'previous_10_game_team1_player3_average_kills',
       'previous_10_game_team1_player3_average_deaths',
       'previous_10_game_team1_player3_average_assists',
       'previous_10_game_team1_player3_average_adr',
       'previous_10_game_team1_player3_average_kast',
       'previous_10_game_team1_player3_average_kddiff',
       'previous_10_game_team1_player4_average_kills',
       'previous_10_game_team1_player4_average_deaths',
       'previous_10_game_team1_player4_average_assists',
       'previous_10_game_team1_player4_average_adr',
       'previous_10_game_team1_player4_average_kast',
       'previous_10_game_team1_player4_average_kddiff',
       'previous_10_game_team1_player5_average_kills',
       'previous_10_game_team1_player5_average_deaths',
       'previous_10_game_team1_player5_average_assists',
       'previous_10_game_team1_player5_average_adr',
       'previous_10_game_team1_player5_average_kast',
       'previous_10_game_team1_player5_average_kddiff',
       'previous_10_game_team2_player1_average_kills',
       'previous_10_game_team2_player1_average_deaths',
       'previous_10_game_team2_player1_average_assists',
       'previous_10_game_team2_player1_average_adr',
       'previous_10_game_team2_player1_average_kast',
       'previous_10_game_team2_player1_average_kddiff',
       'previous_10_game_team2_player2_average_kills',
       'previous_10_game_team2_player2_average_deaths',
       'previous_10_game_team2_player2_average_assists',
       'previous_10_game_team2_player2_average_adr',
       'previous_10_game_team2_player2_average_kast',
       'previous_10_game_team2_player2_average_kddiff',
       'previous_10_game_team2_player3_average_kills',
       'previous_10_game_team2_player3_average_deaths',
       'previous_10_game_team2_player3_average_assists',
       'previous_10_game_team2_player3_average_adr',
       'previous_10_game_team2_player3_average_kast',
       'previous_10_game_team2_player3_average_kddiff',
       'previous_10_game_team2_player4_average_kills',
       'previous_10_game_team2_player4_average_deaths',
       'previous_10_game_team2_player4_average_assists',
       'previous_10_game_team2_player4_average_adr',
       'previous_10_game_team2_player4_average_kast',
       'previous_10_game_team2_player4_average_kddiff',
       'previous_10_game_team2_player5_average_kills',
       'previous_10_game_team2_player5_average_deaths',
       'previous_10_game_team2_player5_average_assists',
       'previous_10_game_team2_player5_average_adr',
       'previous_10_game_team2_player5_average_kast',
       'previous_10_game_team2_player5_average_kddiff',
       'team1_previous_10_average_map_score',
       'team2_previous_10_average_map_score', 'bestOf_3.0', 'bestOf_5.0'],
      dtype='object')

array([[ 0.00832452, -0.07052401,  0.02349586,  0.03153651, -0.06151086,
         0.05337037,  0.11259901,  0.05607004, -0.00598368, -0.11070366,
         0.08146329,  0.06388132, -0.07559331, -0.04445793, -0.02621948,
         0.09215566,  0.1251056 , -0.03358672,  0.08331954,  0.04459119,
        -0.02542251,  0.00229915, -0.03132181,  0.04478758, -0.0112093 ,
        -0.04586316, -0.01608251,  0.04481548,  0.01772425,  0.02003342,
        -0.04006914,  0.00741921, -0.00059321, -0.00227904, -0.05148124,
        -0.03948428, -0.01149988, -0.00659475,  0.0707451 , -0.06813123,
         0.00627204, -0.00588689,  0.04704409,  0.05169276,  0.00951998,
        -0.08849157, -0.05815084,  0.00676489, -0.11485957, -0.06247819,
         0.05344183,  0.03059702, -0.02857306, -0.06111773, -0.04174765,
         0.00516888,  0.04724857, -0.00877488,  0.06637276, -0.03944105,
         0.06210661, -0.11591419, -0.17420558, -0.11211579]])

In [15]:
weights = pd.DataFrame()
weights["Feature"] = X_train.columns
weights["Weight"] = lr.coef_[0]
weights = weights.sort_values(by="Weight", ascending = False)
weights.head(10)

                                           Feature    Weight
16     previous_10_game_team1_player3_average_kast  0.125106
6     previous_10_game_team1_player2_average_kills  0.112599
15      previous_10_game_team1_player3_average_adr  0.092156
18    previous_10_game_team1_player4_average_kills  0.083320
10     previous_10_game_team1_player2_average_kast  0.081463
38  previous_10_game_team2_player2_average_assists  0.070745
58     previous_10_game_team2_player5_average_kast  0.066373
11   previous_10_game_team1_player2_average_kddiff  0.063881
60             team1_previous_10_average_map_score  0.062107
7    previous_10_game_team1_player2_average_deaths  0.056070

In [16]:
weights.tail(10)

                                          Feature    Weight
49  previous_10_game_team2_player4_average_deaths -0.062478
39     previous_10_game_team2_player2_average_adr -0.068131
1   previous_10_game_team1_player1_average_deaths -0.070524
12   previous_10_game_team1_player3_average_kills -0.075593
45     previous_10_game_team2_player3_average_adr -0.088492
9      previous_10_game_team1_player2_average_adr -0.110704
63                                     bestOf_5.0 -0.112116
48   previous_10_game_team2_player4_average_kills -0.114860
61            team2_previous_10_average_map_score -0.115914
62                                     bestOf_3.0 -0.174206

It is giving the highest absolute weight to best of 3.0, player3_kast, team2_previous_10,average_map_score, and so forth. Totally contrary to my guess, the model seems to highly value bestOf. It also seems to have trouble keeping stats influences consistent in the sense that for some reason team 1 player 3 kast is significantly more heavily weighted than the other team 1 players' kast. Player 3 is arbitrary, so it does not make sense that player 3 should have more weight than others for the kast category. I assume this will improve when we aggregate to team-level stats since we are trying to make a team-level prediction. If the players were ordered by performance, such as where player 1 is always the player with the highest stats, then maybe it could give a more fair assessment to the weights, but with the arbitrary ordering of players, it is hard to assign a consistent weight. This ordering issue will be removed with team-level aggregation of stats. Collinearity might be an issue as well and could explain why some stats like team 1 player 2 average adr contributes a negative weight which we wouldn't expect.

I assume if we add the interaction term of how the 5 players stats interact per team, this will be much more predictive and the weight will be more meaningful for a team-level prediction.